import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ChatProvider } from "@/app/src/context/chatcontext";
import WhatsAppLayout from "@/app/src/whatsaplayout";
import ClientLayout from "@/app/src/notification";
import IncomingCall from "./src/incomingcall";
import 'react-toastify/dist/ReactToastify.css';
import Tost from "./src/compoent/tost"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated byb create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <head>
        <link rel="manifest" href="/login.jpg" />
        <link rel="icon" href="/icons/icon-192x192.png" />
        <meta name="theme-color" content="#000000" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <ChatProvider>
          <WhatsAppLayout />
          <ClientLayout>
            {children}
          </ClientLayout>
          <IncomingCall />
          <Tost />
        </ChatProvider>


      </body>
    </html>
  );
}
