import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ChatProvider } from "@/app/src/context/chatcontext";
import WhatsAppLayout from "@/app/src/whatsaplayout";
import ClientLayout from "@/app/src/notification";
import IncomingCall from "./src/incomingcall";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated byb create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <ChatProvider>
          <WhatsAppLayout />
          <ClientLayout>
            {children}
          </ClientLayout>
          <IncomingCall />
        </ChatProvider>

      </body>
    </html>
  );
}
